get http://localhost:3000
###

get http://localhost:3000/users
###
post http://localhost:3000/create_user
Content-Type: application/json

{
   "name": "Tuba",
   "age": 33
}

###
post http://localhost:3000/create_user
Content-Type: application/json

{
   "name": "sarah",
   "age": 6
}


