get http://localhost:3000/users/specific
###

get http://localhost:3000/users/test_users

###

post http://localhost:3000/users/create_user
Content-Type: application/json

{
   "name": "sarah",
   "age": 34
}

###

post http://localhost:3000/users/create_user
Content-Type: application/json

{
   "name": "sarah",
   "age": 6
}

###

get http://localhost:3000/users/getUsers
###

get http://localhost:3000/users/getOneUser/